create table if not exists matches (
 id bigint generated by default as identity primary key,
 kickoff_at timestamptz not null,
 home_team text not null, away_team text not null,
 home_goals integer, away_goals integer,
 data_available_at timestamptz,
 created_at timestamptz not null default now()
);
create table if not exists predictions (
 id bigint generated by default as identity primary key,
 match_id bigint not null references matches(id) on delete cascade,
 model_version text not null,
 predicted_at timestamptz not null default now(),
 home_xg double precision, away_xg double precision,
 p_home double precision not null, p_draw double precision not null, p_away double precision not null,
 actual_outcome text, brier double precision, log_loss double precision
);
create index if not exists idx_matches_kickoff on matches(kickoff_at);
create index if not exists idx_predictions_match on predictions(match_id);
